// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD-RL5FDNkUGDkk-Gc8erAxKZ0qFjp_FBQ',
    appId: '1:894892281409:web:5284b243920aae702ec0c0',
    messagingSenderId: '894892281409',
    projectId: 'tracking-app-76373',
    authDomain: 'tracking-app-76373.firebaseapp.com',
    databaseURL: 'https://tracking-app-76373-default-rtdb.firebaseio.com',
    storageBucket: 'tracking-app-76373.appspot.com',
    measurementId: 'G-DETBSFKKCW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAWHnBsYApOmunH-dAofSTQIsr096uN7lE',
    appId: '1:894892281409:android:f72abf9c20cd7b302ec0c0',
    messagingSenderId: '894892281409',
    projectId: 'tracking-app-76373',
    databaseURL: 'https://tracking-app-76373-default-rtdb.firebaseio.com',
    storageBucket: 'tracking-app-76373.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDPHqL-Rv5J-TfrrUgnISUkn3YtW-JSanA',
    appId: '1:894892281409:ios:93f5351d3c73166d2ec0c0',
    messagingSenderId: '894892281409',
    projectId: 'tracking-app-76373',
    databaseURL: 'https://tracking-app-76373-default-rtdb.firebaseio.com',
    storageBucket: 'tracking-app-76373.appspot.com',
    iosClientId: '894892281409-4h3m6744mmuasrn0o5uhes6tdkq3lvt3.apps.googleusercontent.com',
    iosBundleId: 'com.example.trackingApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDPHqL-Rv5J-TfrrUgnISUkn3YtW-JSanA',
    appId: '1:894892281409:ios:93f5351d3c73166d2ec0c0',
    messagingSenderId: '894892281409',
    projectId: 'tracking-app-76373',
    databaseURL: 'https://tracking-app-76373-default-rtdb.firebaseio.com',
    storageBucket: 'tracking-app-76373.appspot.com',
    iosClientId: '894892281409-4h3m6744mmuasrn0o5uhes6tdkq3lvt3.apps.googleusercontent.com',
    iosBundleId: 'com.example.trackingApp',
  );
}
